name: Update Resume Gist

on: push

jobs:
  update-resume-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Update Resume Gist
        uses: exuanbo/actions-deploy-gist@47697fceaeea2006a90594ee24eb9cd0a1121ef8 # v1.1.4
        with:
          token: ${{ secrets.TOKEN }}
          gist_id: 51d4f54536e437ef27bd2181b59c95d5
          file_path: resume.json
